# Generated by Django 5.0.1 on 2024-10-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("print_plan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="printplan",
            name="gcode_file",
            field=models.FileField(
                blank=True, null=True, upload_to="generated/gcode_file"
            ),
        ),
    ]
