# Generated by Django 5.0.1 on 2024-10-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("print_plan", "0003_alter_printplan_gcode_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printplan",
            name="gcode_file",
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=""),
        ),
    ]
