version: "3.9"

services:
  api:
    container_name: amui-api
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./api:/home/api

      # Links bundle to templates folder.
      - bundle:/home/api/static
    ports:
      - 8000:8000
    tty: true
    depends_on:
      - sql
      - web
    command: bash ./entrypoint.sh

  web:
    container_name: amui-web
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      # https://stackoverflow.com/a/65265986/10521456
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./web:/home/web

      # Creates a separate volume for node_modules otherwise next.js won't start
      - web_node_modules:/home/web/node_modules

      # Links bundle from build output to api server.
      - bundle:/home/web/dist
    tty: true
    ports:
      - 3000:3000
  
  sql:
    container_name: amui-sql
    image: postgres:13
    volumes:
      - sql_data:/var/lib/postgres/data/
    env_file:
      - .env
    ports:
      - 5432:5432

  pgadmin:
    container_name: amui-pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - 5050:5050
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - sql

  module-example:
    container_name: amui-module-example
    build:
      context: ./module/example
      dockerfile: Dockerfile
    tty: true

volumes:
  bundle:
  pgadmin:
  sql_data:
  web_node_modules:

    