# Generated by Django 5.0.1 on 2024-10-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("part", "0003_remove_part_file_partfile_part_part_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="partfile",
            name="thumbnail",
            field=models.FileField(
                blank=True, null=True, upload_to="uploads/part_file"
            ),
        ),
        migrations.AlterField(
            model_name="partfile",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="uploads/part_file"
            ),
        ),
    ]
