# Generated by Django 5.0.1 on 2024-10-17 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("part", "0004_partfile_thumbnail_alter_partfile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="part_file",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="part.partfile",
            ),
            preserve_default=False,
        ),
    ]
