# Generated by Django 5.0.1 on 2024-03-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("machine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="specification",
            name="company",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="specification",
            name="company_logo_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="specification",
            name="image_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
