from django.db import models

# Create your models here.
class GeometryRecord(models.Model):
    material = models.CharField(max_length=100)
    process = models.CharField(max_length=100)
    sub_process = models.CharField(max_length=100, blank=True, null=True)
    power = models.FloatField(blank=True, null=True)
    velocity = models.FloatField(blank=True, null=True)
    hatch_spacing = models.FloatField(blank=True, null=True)
    melt_pool_depth = models.FloatField(blank=True, null=True)
    melt_pool_width = models.FloatField(blank=True, null=True)
    melt_pool_length = models.FloatField(blank=True, null=True)
    depth_over_length = models.FloatField(blank=True, null=True)
    depth_over_width = models.FloatField(blank=True, null=True)
    length_over_width = models.FloatField(blank=True, null=True)
    energy_joules_over_mm = models.FloatField(blank=True, null=True)
    energy_joules_over_mm_cubed = models.FloatField(blank=True, null=True)
    layer_thickness = models.FloatField(blank=True, null=True)
    beam_diameter = models.FloatField(blank=True, null=True)
    absorption_coefficient = models.FloatField(blank=True, null=True)
    absorption_coefficient_2 = models.FloatField(blank=True, null=True)
    density = models.FloatField(blank=True, null=True)
    specific_heat_capacity = models.FloatField(blank=True, null=True)
    k = models.FloatField(blank=True, null=True)
    melting_temperature = models.FloatField(blank=True, null=True)
    minimal_absorptivity = models.FloatField(blank=True, null=True)
    melt_pool_shape = models.CharField(max_length=100, blank=True, null=True)
    spatter = models.FloatField(blank=True, null=True)
    weight_percent_Y = models.FloatField(blank=True, null=True)
    weight_percent_Zn = models.FloatField(blank=True, null=True)
    weight_percent_Mg = models.FloatField(blank=True, null=True)
    weight_percent_Si = models.FloatField(blank=True, null=True)
    weight_percent_Al = models.FloatField(blank=True, null=True)
    weight_percent_Sn = models.FloatField(blank=True, null=True)
    weight_percent_Zr = models.FloatField(blank=True, null=True)
    weight_percent_W = models.FloatField(blank=True, null=True)
    weight_percent_Ti = models.FloatField(blank=True, null=True)
    weight_percent_V = models.FloatField(blank=True, null=True)
    weight_percent_Co = models.FloatField(blank=True, null=True)
    weight_percent_Cu = models.FloatField(blank=True, null=True)
    weight_percent_Ta = models.FloatField(blank=True, null=True)
    weight_percent_Nb = models.FloatField(blank=True, null=True)
    weight_percent_Ni = models.FloatField(blank=True, null=True)
    weight_percent_Cr = models.FloatField(blank=True, null=True)
    weight_percent_Fe = models.FloatField(blank=True, null=True)
    weight_percent_Mn = models.FloatField(blank=True, null=True)
    weight_percent_Mo = models.FloatField(blank=True, null=True)
    D10 = models.FloatField(blank=True, null=True)
    D50 = models.FloatField(blank=True, null=True)
    D90 = models.FloatField(blank=True, null=True)
    paper_id = models.CharField(blank=True, null=True)
    paper_url = models.URLField(blank=True, null=True)
    porosity = models.IntegerField(blank=True, null=True)
    relative_density = models.FloatField(blank=True, null=True)
    comments = models.TextField(null=True, blank=True)
    unknown = models.IntegerField(null=True)

class ClassificationRecord(models.Model):
    material = models.CharField(max_length=255)
    process = models.CharField(max_length=255)
    power = models.IntegerField(blank=True, null=True)
    velocity = models.IntegerField(blank=True, null=True)
    hatch_spacing = models.IntegerField(blank=True, null=True)
    energy_density = models.FloatField(null=True, blank=True)
    layer_thickness = models.IntegerField(blank=True, null=True)
    beam_diameter = models.IntegerField(blank=True, null=True)
    density = models.FloatField(null=True, blank=True)
    specific_heat_capacity = models.FloatField(null=True, blank=True)
    k = models.FloatField(null=True, blank=True)
    melting_temperature = models.IntegerField(null=True, blank=True)
    absorption_coefficient = models.FloatField(null=True, blank=True)
    minimal_absorptivity = models.FloatField(null=True, blank=True)
    melt_pool_shape = models.CharField(max_length=255, null=True, blank=True)
    spatter = models.CharField(max_length=255, null=True, blank=True)
    weight_percent_Zn = models.FloatField(null=True, blank=True)
    weight_percent_Mg = models.FloatField(null=True, blank=True)
    weight_percent_Si = models.FloatField(null=True, blank=True)
    weight_percent_Al = models.FloatField(null=True, blank=True)
    weight_percent_Sn = models.FloatField(null=True, blank=True)
    weight_percent_Zr = models.FloatField(null=True, blank=True)
    weight_percent_W = models.FloatField(null=True, blank=True)
    weight_percent_Ti = models.FloatField(null=True, blank=True)
    weight_percent_V = models.FloatField(null=True, blank=True)
    weight_percent_Co = models.FloatField(null=True, blank=True)
    weight_percent_Cu = models.FloatField(null=True, blank=True)
    weight_percent_Ta = models.FloatField(null=True, blank=True)
    weight_percent_Nb = models.FloatField(null=True, blank=True)
    weight_percent_Ni = models.FloatField(null=True, blank=True)
    weight_percent_Cr = models.FloatField(null=True, blank=True)
    weight_percent_Fe = models.FloatField(null=True, blank=True)
    weight_percent_Mn = models.FloatField(null=True, blank=True)
    weight_percent_Mo = models.FloatField(null=True, blank=True)
    paper_id = models.CharField(blank=True, null=True)
    paper_url = models.URLField(blank=True, null=True)
    porosity = models.FloatField(null=True, blank=True)
    relative_density = models.FloatField(null=True, blank=True)
    comments = models.TextField(null=True, blank=True)
