# Generated by Django 5.0.1 on 2024-01-29 19:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("melt_pool", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MeltPoolClassification",
            new_name="Classification",
        ),
        migrations.RenameModel(
            old_name="MeltPoolGeometry",
            new_name="Geometry",
        ),
    ]
