# Generated by Django 5.0.1 on 2024-02-05 01:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("melt_pool", "0002_rename_meltpoolclassification_classification_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Classification",
            new_name="ClassificationRecord",
        ),
        migrations.RenameModel(
            old_name="Geometry",
            new_name="GeometryRecord",
        ),
    ]
