# Generated by Django 5.0.1 on 2024-02-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("melt_pool", "0003_rename_classification_classificationrecord_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="geometryrecord",
            name="unknown",
            field=models.IntegerField(null=True),
        ),
    ]
