# Generated by Django 5.0.1 on 2024-02-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("melt_pool", "0004_geometryrecord_unknown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classificationrecord",
            name="paper_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="geometryrecord",
            name="paper_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
