# Generated by Django 5.0.1 on 2024-02-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("melt_pool", "0005_alter_classificationrecord_paper_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classificationrecord",
            name="beam_diameter",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="classificationrecord",
            name="hatch_spacing",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="classificationrecord",
            name="layer_thickness",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="classificationrecord",
            name="power",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="classificationrecord",
            name="velocity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="geometryrecord",
            name="hatch_spacing",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="geometryrecord",
            name="power",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="geometryrecord",
            name="velocity",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
