# Generated by Django 5.0.1 on 2024-02-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("melt_pool", "0006_alter_classificationrecord_beam_diameter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classificationrecord",
            name="paper_id",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="geometryrecord",
            name="paper_id",
            field=models.CharField(blank=True, null=True),
        ),
    ]
