# Generated by Django 5.0.1 on 2024-09-26 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("build_profile", "0001_initial"),
        ("material", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildprofile",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="material.material",
            ),
        ),
    ]
