# Generated by Django 5.0.1 on 2024-09-28 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("build_profile", "0002_buildprofile_material"),
        ("machine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildprofile",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="machine.machine",
            ),
        ),
    ]
