# Generated by Django 5.0.1 on 2024-10-18 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("build_profile", "0003_buildprofile_machine"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="buildprofile",
            options={"ordering": ["name", "created_on", "updated_on"]},
        ),
        migrations.RenameField(
            model_name="buildprofile",
            old_name="title",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="buildprofile",
            name="description",
        ),
    ]
