# Generated by Django 5.0.1 on 2024-10-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("build_profile", "0004_alter_buildprofile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildprofile",
            name="hatch_spacing",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="buildprofile",
            name="layer_thickness",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=8, null=True
            ),
        ),
    ]
