# Generated by Django 5.0.1 on 2024-10-20 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("build_profile", "0006_alter_buildprofile_hatch_spacing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildprofile",
            name="power",
            field=models.IntegerField(
                default=100,
                help_text="Enter a power value (Watts) between 0 and 10,000",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="buildprofile",
            name="hatch_spacing",
            field=models.DecimalField(decimal_places=6, default=5e-05, max_digits=8),
        ),
        migrations.AlterField(
            model_name="buildprofile",
            name="layer_thickness",
            field=models.DecimalField(decimal_places=6, default=0.5, max_digits=8),
        ),
    ]
