# Generated by Django 5.0.1 on 2024-09-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("flow_3d_name", models.CharField(default="Unknown", max_length=100)),
                ("uns_id", models.CharField(default="Unknown", max_length=16)),
                ("density_g_cm_3", models.FloatField(blank=True, null=True)),
                ("specific_heat_erg_g_K", models.FloatField(blank=True, null=True)),
                (
                    "thermal_conductivity_erg_cm_s_K",
                    models.FloatField(blank=True, null=True),
                ),
                ("viscosity_g_cm_s", models.FloatField(blank=True, null=True)),
                ("solidus_temperature_K", models.FloatField(blank=True, null=True)),
                ("liquidus_temperature_K", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
