name: web

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-web:
    runs-on: ubuntu-latest
    container:
      image: node:20-alpine

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install `node_modules` 
      run: npm install

    - name: Build Webpack Bundle
      run: npm run build

    - name: Run ESLint
      run: npm run lint
